services:
  athena_trino_php:
    container_name: athena_trino_php
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - aws_molpay

networks:
  aws_molpay:
    external: true